{
 "title": "SysEleven - Quotas",
 "description": "Dashboard for SysEleven Exporter",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   { "name": "project", "label": "project_id", "query": { "query": "label_values(project)" } },
   { "name": "region", "query": { "query": "label_values(region)" } }
  ]
 },
 "panels": [
  {
   "title": "SysEleven - Compute Cores",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "targets": [
    {}
   ]
  },
  {
   "title": "SysEleven - Compute Cores",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum((syseleven_compute_cores_used{project=\"$project\"} / syseleven_compute_cores_total{project=\"$project\"}) * 100) by(region, project)",
     "legendFormat": "{{region}} | {{project}}"
    }
   ]
  },
  {
   "title": "SysEleven - Used Compute Cores",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "CPUs" } },
   "yaxes": [
    { "format": "CPUs" }
   ],
   "targets": [
    {
     "expr": "sum(syseleven_compute_cores_used{project=\"$project\",region=\"$region\"}) by(region, project) ",
     "legendFormat": "{{region}} | {{project}}"
    }
   ]
  },
  {
   "title": "SysEleven - Total Compute Cores",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "CPUs" } },
   "yaxes": [
    { "format": "CPUs" }
   ],
   "targets": [
    {
     "expr": "sum(syseleven_compute_cores_total{project=\"$project\",region=\"$region\"}) by(region, project) ",
     "legendFormat": "{{region}} | {{project}}"
    }
   ]
  },
  {
   "title": "SysEleven - Compute Ram",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "targets": [
    {}
   ]
  },
  {
   "title": "SysEleven - Compute Ram",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum((syseleven_compute_ram_used_megabytes{project=\"$project\"} / syseleven_compute_ram_total_megabytes{project=\"$project\"}) * 100) by(region, project)",
     "legendFormat": "{{region}} | {{project}}"
    }
   ]
  },
  {
   "title": "SysEleven - Used Compute Ram",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "sum(syseleven_compute_ram_used_megabytes{project=\"$project\",region=\"$region\"}) by(region, project) ",
     "legendFormat": "{{region}} | {{project}}"
    }
   ]
  },
  {
   "title": "SysEleven - Total Compute Ram",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "sum(syseleven_compute_ram_total_megabytes{project=\"$project\",region=\"$region\"}) by(region, project) ",
     "legendFormat": "{{region}} | {{project}}"
    }
   ]
  },
  {
   "title": "SysEleven - S3 Space",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "targets": [
    {}
   ]
  },
  {
   "title": "SysEleven - S3 Space",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum((syseleven_s3_space_used_bytes{project=\"$project\"}/ syseleven_s3_space_total_bytes{project=\"$project\"}) * 100) by(region, project)",
     "legendFormat": "{{region}} | {{project}}"
    }
   ]
  },
  {
   "title": "SysEleven - Used S3 Space",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(syseleven_s3_space_used_bytes{project=\"$project\",region=\"$region\"}) by(region, project) ",
     "legendFormat": "{{region}} | {{project}}"
    }
   ]
  },
  {
   "title": "SysEleven - Total S3 Space",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(syseleven_s3_space_total_bytes{project=\"$project\"}) by(region, project) ",
     "legendFormat": "{{region}} | {{project}}"
    }
   ]
  },
  {
   "title": "SysEleven - Volume Space",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "targets": [
    {}
   ]
  },
  {
   "title": "SysEleven - Volume Space",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum((syseleven_volume_space_used_gigabytes{project=\"$project\"}/ syseleven_volume_space_total_gigabytes{project=\"$project\"}) * 100) by(region, project)",
     "legendFormat": "{{region}} | {{project}}"
    }
   ]
  },
  {
   "title": "SysEleven - Used Volume Space",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(syseleven_volume_space_used_gigabytes{project=\"$project\",region=\"$region\"}) by(region, project) ",
     "legendFormat": "{{region}} | {{project}}"
    }
   ]
  },
  {
   "title": "SysEleven - Total Volume Space",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(syseleven_volume_space_total_gigabytes{project=\"$project\",region=\"$region\"}) by(region, project) ",
     "legendFormat": "{{region}} | {{project}}"
    }
   ]
  },
  {
   "title": "SysEleven - Volume Volumes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "targets": [
    {}
   ]
  },
  {
   "title": "SysEleven - Volume Volumes",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum((syseleven_volume_volumes_used{project=\"$project\"}/ syseleven_volume_volumes_total{project=\"$project\"}) * 100) by(region, project)",
     "legendFormat": "{{region}} | {{project}}"
    }
   ]
  },
  {
   "title": "SysEleven - Used Volumes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(syseleven_volume_volumes_used{project=\"$project\",region=\"$region\"}) by(region, project) ",
     "legendFormat": "{{region}} | {{project}}"
    }
   ]
  },
  {
   "title": "SysEleven - Total Volumes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(syseleven_volume_volumes_total{project=\"$project\",region=\"$region\"}) by(region, project) ",
     "legendFormat": "{{region}} | {{project}}"
    }
   ]
  },
  {
   "title": "SysEleven - Compute Instances",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "collapsed": true,
   "targets": [
    {}
   ]
  },
  {
   "title": "SysEleven - Compute Instances",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum((syseleven_compute_instances_used{project=\"$project\"}/syseleven_compute_instances_total{project=\"$project\"}) * 100) by(region, project)",
     "legendFormat": "{{region}} | {{project}}"
    }
   ]
  },
  {
   "title": "SysEleven - Used Compute Instances",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "Instances" } },
   "yaxes": [
    { "format": "Instances" }
   ],
   "targets": [
    {
     "expr": "sum(syseleven_compute_instances_used{project=\"$project\",region=\"$region\"}) by(region, project) ",
     "legendFormat": "{{region}} | {{project}}"
    }
   ]
  },
  {
   "title": "SysEleven - Total Compute Instances",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "Instances" } },
   "yaxes": [
    { "format": "Instances" }
   ],
   "targets": [
    {
     "expr": "sum(syseleven_compute_instances_total{project=\"$project\",region=\"$region\"}) by(region, project) ",
     "legendFormat": "{{region}} | {{project}}"
    }
   ]
  },
  {
   "title": "SysEleven - Network LoadBalancers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 },
   "collapsed": true,
   "targets": [
    {}
   ]
  },
  {
   "title": "SysEleven - Network Floating IPs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 },
   "collapsed": true,
   "targets": [
    {}
   ]
  },
  {
   "title": "SysEleven - Network Floating IPs",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum((syseleven_network_floating_ips_used{project=\"$project\"}/syseleven_network_floating_ips_total{project=\"$project\"}) * 100) by(region, project)",
     "legendFormat": "{{region}} | {{project}}"
    }
   ]
  },
  {
   "title": "SysEleven - Used Network Floating IPs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "IPs" } },
   "yaxes": [
    { "format": "IPs" }
   ],
   "targets": [
    {
     "expr": "sum(syseleven_network_floating_ips_used{project=\"$project\",region=\"$region\"}) by(region, project) ",
     "legendFormat": "{{region}} | {{project}}"
    }
   ]
  },
  {
   "title": "SysEleven - Total Network Floating IPs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "IPs" } },
   "yaxes": [
    { "format": "IPs" }
   ],
   "targets": [
    {
     "expr": "sum(syseleven_network_floating_ips_total{project=\"$project\",region=\"$region\"}) by(region, project) ",
     "legendFormat": "{{region}} | {{project}}"
    }
   ]
  },
  {
   "title": "SysEleven - DNS Zones",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 },
   "collapsed": true,
   "targets": [
    {}
   ]
  },
  {
   "title": "SysEleven - DNS Zones",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum((syseleven_dns_zones_used{project=\"$project\"}/syseleven_dns_zones_total{project=\"$project\"}) * 100) by(region, project)",
     "legendFormat": "{{region}} | {{project}}"
    }
   ]
  },
  {
   "title": "SysEleven - Used DNS Zones",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "Zones" } },
   "yaxes": [
    { "format": "Zones" }
   ],
   "targets": [
    {
     "expr": "sum(syseleven_dns_zones_used{project=\"$project\",region=\"$region\"}) by(region, project) ",
     "legendFormat": "{{region}} | {{project}}"
    }
   ]
  },
  {
   "title": "SysEleven - Total DNS Zones",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "Zones" } },
   "yaxes": [
    { "format": "Zones" }
   ],
   "targets": [
    {
     "expr": "sum(syseleven_dns_zones_total{project=\"$project\",region=\"$region\"}) by(region, project) ",
     "legendFormat": "{{region}} | {{project}}"
    }
   ]
  }
 ]
}